import numpy as np
a=np.array([1,2,3,4,5])
b=np.array(range(1,6))
c=np.arange(1,6)
print(f'a:{a}')
print(f'b:{b}')
print(f'c:{c}')
print('a.dtype:',a.dtype)
print('type(a):',type(a))
a1=np.array([1,2,3,4,5],'int64')
print(f'array中元素的数据类型:',a1.dtype)
print('array的维度/形状:',b.shape)
print('array的维度的数目:',a.ndim)
print('array中所有元素的数目:',a.size)
